<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"客户管理",
                        "menuJump":"列表",
                        "tableName":"kehu"
                    }
                ],
                "menu":"客户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"地皮管理",
                        "menuJump":"列表",
                        "tableName":"dipi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"地皮留言管理",
                        "menuJump":"列表",
                        "tableName":"dipiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"地皮收藏管理",
                        "menuJump":"列表",
                        "tableName":"dipiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"地皮订单管理",
                        "menuJump":"列表",
                        "tableName":"dipiOrder"
                    }
                ],
                "menu":"地皮管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"作物状态管理",
                        "menuJump":"列表",
                        "tableName":"zuowuzhuangtai"
                    }
                ],
                "menu":"作物状态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"邮寄订单管理",
                        "menuJump":"列表",
                        "tableName":"dingdan"
                    }
                ],
                "menu":"邮寄订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"作物类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZuowu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"作物阶段类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZuowuzhuangtaiJieduan"
                    }

                ],
                "menu":"基础数据管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图管理"
            }
			,
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地皮管理",
                        "menuJump":"列表",
                        "tableName":"dipi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地皮留言管理",
                        "menuJump":"列表",
                        "tableName":"dipiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地皮收藏管理",
                        "menuJump":"列表",
                        "tableName":"dipiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"地皮订单管理",
                        "menuJump":"列表",
                        "tableName":"dipiOrder"
                    }
                ],
                "menu":"地皮管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"作物状态管理",
                        "menuJump":"列表",
                        "tableName":"zuowuzhuangtai"
                    }
                ],
                "menu":"作物状态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"邮寄订单管理",
                        "menuJump":"列表",
                        "tableName":"dingdan"
                    }
                ],
                "menu":"邮寄订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"客户",
        "tableName":"kehu"
    }
];

var hasMessage = '';
